### ISSUE TITLE
Question about Performance

### ISSUE THREAD

**Issue by n3ssi3** [lincolnloop/amygdala#20]
Do you have experience about handling big data sets?
I found this blog post: http://josh.zeigler.us/technology/web-development/how-big-is-too-big-for-json/
Do you have numbers like that with Amygdala ?

**Comment by unbracketed** [comment]
We haven't done any specific performance testing. The main use of this library for us has been to remove some boilerplate from front-end code that needs to interact with a REST-based API. Our main use case has been for infrequent AJAX'ed CRUD operations.
